import Head from 'next/head';
import Image from 'next/image';

// Chosen Components:
import Header from '../components/Header';
import Navbar from '../components/Navbar';
import styles from '../styles/Home.module.css';
import { CardBox, CardMoves, Pokeball } from '../components/Cards';

export default function Details() {
	return (
		<>
			<Head>
				<title>Poke Details</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Navbar title='Pokemon Detail' />
			<main className='align-items-center justify-content-center container py-4'>
				<Header title='Pokemon' />

				<CardBox picture={'/trash.svg'} />

				<CardMoves moves='Thunderbolt, Thunder, Thunder Wave, Thunder Punch' />

				<Pokeball />
			</main>


			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'>
					Powered by{' '}
					<span className={styles.logo}>
						<Image
							src='/vercel.svg'
							alt='Vercel Logo'
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</>
	);
}
