import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div style={{ backgroundColor: '#F25430' }}>
			<Head>
				<title>Home</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<div className='text-center'>
					<Image
						src='/Pokemon.svg'
						alt='Pokemon-logo'
						width={200}
						height={100}
					/>

					<h2 className='text-white'>Mini Games</h2>

					<a href='#'>
						<div className='border border-5 rounded-pill p-2 fw-bold text-white text-uppercase my-3'>
							<Link href='/ListPokemon'>Game Start</Link>
						</div>
					</a>
				</div>
			</main>
		</div>
	);
}
