import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Home</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Welcome to Pokemon World!</h1>

				<div className={styles.grid}>
					<a href='#'>
						<Link href='/Details'>
							{/* <div className={Pokemon.listcard}> */}
							<h2>Go to Details</h2>
							{/* </div> */}
						</Link>
					</a>

					<a href='#'>
						<Link href='/ListPokemon'>
							<div className='card bg-danger'>
								<h2>Go to List Pokemon</h2>
							</div>
						</Link>
					</a>
					<a href='#'>
						<Link href='/MyPokemon'>
							<div className={styles.card}>
								<h2>Go to MyPokemon</h2>
							</div>
						</Link>
					</a>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'>
					Powered by{' '}
					<span className={styles.logo}>
						<Image
							src='/vercel.svg'
							alt='Vercel Logo'
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	);
}
