import Head from 'next/head';
import Header from '../components/Header';
import Image from 'next/image';

// Chosen Components:
import Navbar from '../components/Navbar';
import Swal from 'sweetalert2';
import Footer from '../components/Footer';
import { useEffect, useState } from 'react';
import { CardList } from '../components/Cards';

export default function MyPokemon() {
	const [poke, setPoke] = useState([]);

	useEffect(() => {
		setPoke(JSON.parse(localStorage.getItem('ownedPokemon')));
	}, []);

	const deletePoke = () => {
		Swal.fire({
			title: 'Are you sure?',
			text: 'You will not be able to recover this Pokemon!',
			icon: 'warning',
			showCancelButton: true,
			confirmButtonColor: '#d33',
			cancelButtonColor: '#3085d6',
			confirmButtonText: 'Release it!',
			cancelButtonText: 'Cancel!',
		});
		localStorage.removeItem('ownedPokemon');
		
	};

	return (
		<>
			<Head>
				<title>My Pokemon</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Navbar title='My Pokemon' />
			<main className='align-items-center justify-content-center container py-4'>
				<Header title='My Pokemon List' />


				<div className=''>
					{poke.map((pokemon, index) => {
						return (
							<CardList
								key={index}
								pokeName={pokemon.pokemon}
								box={
									<Image
										src='/trash.svg'
										alt='trash'
										width={40}
										height={40}
										onClick={deletePoke}
									/>
								}
							/>
						);
					})}
				</div>
			</main>

			<Footer />
		</>
	);
}
