import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import styles from '../styles/Home.module.css';

// Chosen Components:
import Navbar from '../components/Navbar';
import { CardList } from '../components/Cards';
import Pagination from '../components/Pagination';
import Swal from 'sweetalert2';

export default function MyPokemon() {
	const deletePoke = () => {
		Swal.fire({
			title: 'Are you sure?',
			text: 'You will not be able to recover this Pokemon!',
			icon: 'warning',
			showCancelButton: true,
			confirmButtonColor: '#d33',
			cancelButtonColor: '#3085d6',
			confirmButtonText: 'Release it!',
			cancelButtonText: 'Cancel!',
			reverseButtons: true,
		}).then((result) => {
			if (result.value) {
				Swal.fire(
					'Released!',
					'Your Pokemon just ran away.',
					'success'
				);
			}
		});
	};
	return (
		<>
			<Head>
				<title>My Pokemon</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Navbar title='My Pokemon' />
			<main className='align-items-center justify-content-center container py-4'>
				<Header title='My Pokemon List' />

				<CardList
					name='Pikachu'
					type='Electric'
					setName='Budi'
					onClick={deletePoke}
					box={
						<Image
							src='/trash.svg'
							alt='trash'
							width={30}
							height={30}></Image>
					}
				/>
				<CardList
					name='Raikou'
					type='Electric'
					setName='Rudy'
					onClick={deletePoke}
					box={
						<Image
							src='/trash.svg'
							alt='trash'
							width={30}
							height={30}></Image>
					}
				/>

				<Pagination />
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'>
					Powered by{' '}
					<span className={styles.logo}>
						<Image
							src='/vercel.svg'
							alt='Vercel Logo'
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</>
	);
}
